exclude :test_beg_len, "TypeError: no implicit conversion of Object into Integer"
exclude :test_comparison_when_recursive, "SystemStackError: stack level too deep"
exclude :test_cyclic_range_inspect, "SystemStackError: stack level too deep"
exclude :test_duckrange, "TypeError: no implicit conversion of TestRange::DuckRange into Integer"
exclude :test_each, "NoMethodError: undefined method '<' for nil"
exclude :test_each_with_succ, "NoMethodError: undefined method 'i' for nil"
exclude :test_eqq, "Expected 0..10 to not be === 0..10."
exclude :test_first_last, "TypeError: can't iterate from NilClass"
exclude :test_frozen_initialize, "FrozenError expected but nothing was raised."
exclude :test_include, "hangs"
exclude :test_initialize_twice, "[FrozenError] exception expected, not #<NameError: 'initialize' called twice>."
exclude :test_last_with_redefine_each, "needs investigation"
exclude :test_overlap?, "Expected 1.. to not be overlap? \"a\".."
exclude :test_range_bsearch_for_floats, "very slow: 275.45s on truffleruby 40.0.0-dev-00aab2cb* (2026-07-29), like ruby 4.0.2, Interpreted JVM [x86_64-linux] with AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx: ( 8 vCPUs)"
exclude :test_range_numeric_string, "<[\"9\", \"10\"]> expected but was <[]>."
exclude :test_step_non_numeric_range, "ArgumentError expected but nothing was raised."
exclude :test_step_numeric_range, "[TypeError] exception expected, not #<NoMethodError: undefined method 'step' for nil>."
